# Generated by Django 5.2.6 on 2025-11-02 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.ImageField(default='male.png', upload_to='channel_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_author', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(blank=True, related_name='channel_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('channemessage_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pictureUrl', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='comment_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='social.channel')),
                ('like', models.ManyToManyField(blank=True, related_name='message_likers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
