# Generated by Django 5.2.6 on 2025-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_channel_channelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comment_image/'),
        ),
    ]
