# Generated by Django 5.2.6 on 2025-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_postcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
